version: '3.8'

services:
  flask-api:
    build: .
    container_name: facture-api
    ports:
      - "6000:6000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - PORT=6000
      - API_HOST=0.0.0.0
      - API_TIMEOUT=30
      - LOG_LEVEL=INFO
    volumes:
      - ./config.json:/app/config.json:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - facture-network

  # Optional: Add a reverse proxy with nginx
  nginx:
    image: nginx:alpine
    container_name: facture-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - flask-api
    restart: unless-stopped
    networks:
      - facture-network

networks:
  facture-network:
    driver: bridge

volumes:
  logs:
